# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
- stage: build
  jobs:
  - job: 'BuildAndPush'
    pool:
      vmImage: 'ubuntu-latest'
      name: 'Azure Pipelines'
    steps:
    # Install DotNetSdk 3.x
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'

    # build with Cake
    - task: Bash@3
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/build.sh'
        arguments: '-verbosity=$(cakeVerbosity) -target=$(cakeTaskName) -Configuration=$(buildConfiguration) -Runtime=$(buildRuntime)'

    # Copy PublishDirectory && TestResults To '$(build.artifactstagingdirectory)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
        flattenFolders: false

    # Show Files IN '$(build.artifactstagingdirectory)'    
    - task: CmdLine@2
      inputs:
        script: |
          echo 'Copied Files List In build.artifactstagingdirectory:'
          cd $(build.artifactstagingdirectory)
          ls -R
          echo 'End'
        workingDirectory: '$(Build.ArtifactStagingDirectory)'

    # Publish BuildArtifacts In AzurePipelines
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop2'
        publishLocation: 'pipeline'

  - job: 'PushDockerImage'
    pool:
      vmImage: 'ubuntu-latest'
      name: 'Azure Pipelines'
    variables:
      KB.Container.RegistryNameSpace: 'kane-blake'
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop2'
        targetPath: '$(Pipeline.Workspace)'
    - task: CmdLine@2
      inputs:
        script: |
          cd $(Pipeline.Workspace)
          echo 'Start'
          ls -R
          echo 'End'
          echo Hello world