# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:

# Install DotNetSdk 3.x
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

# build with cake
- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/build.sh'
    arguments: '-verbosity=$(cakeVerbosity) -target=$(cakeTaskName) -Configuration=$(buildConfiguration) -Runtime=$(buildRuntime)'

# Copy Publish directory To '$(build.artifactstagingdirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/publish'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: false

- task: CmdLine@2
  inputs:
    script: |
      echo 'Copied Files List In build.artifactstagingdirectory:'
      cd $(build.artifactstagingdirectory)
      ls -R
      echo 'End'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

# Publish Files To Artifact In Azure Pipeline
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'LightBlog Build Artifact'
    publishLocation: 'Container'
